### ISSUE TITLE
Some names still differ from BWMirror

### ISSUE THREAD

**Issue by JasperGeurtz** [JasperGeurtz/JBWAPI#8]
- BWListener -> BWEventListener
 - ~~BWClient -> Mirror (Ill probably keep this different, so it is clear that JBWAPI is being used instead of BWMirror)~~
 - ~~TextSize -> Text.Size.Enum (wont change this)~~
 - ~~UnitCommand.getType() -> UnitCommand.getType().getUnitCommandType (not changing this to stay consistent with Unit.getType)~~

**Comment by dgant** [comment]
IIRC the return type of whatBuilds changed from Pair to Tuple (or vice versa). Also trivial.

**Comment by JasperGeurtz** [comment]
Fixed in develop branch
